### ISSUE TITLE
Add flag to fqtools validate to output sequence count

### ISSUE THREAD

**Issue by ElDeveloper** [alastair-droop/fqtools#22]
Would there be interest in a adding a flag to `fqtools validate` to optionally output the total count of sequences *if* the records were all valid? I can work on submitting a pull request, but would like a bit of direction on whether you would prefer to have the changes go in `fqtools validate` or `fqtools count` (and add an option to validate) or neither 🥲 .

The motivation is that I need to count sequences and validate records as fast as possible. It seems to me like this information could be available from `fqtools validate` since we have to traverse the file regardless.

**Comment by alastair-droop** [comment]
Thanks for your interest.

`fqtools` will perform most validation whatever it does, so if you are able to run `fqtools count`, then you already know that the file is a valid FASTQ. However, there is no testing that the two headers per read (if present) match, which is a requirement for a valid FASTQ file. However, I've never seen a FASTQ file "in the wild" that even has the 2nd header populated, so I left this out of the standard testing.

Please try a few "invalid" files through `fqtools count` to make sure it catches the invalid cases you're expecting to see, if necessary setting the nucleotide sets you need.

**Comment by ElDeveloper** [comment]
That is really good to hear. Thanks so much for your explanation. If I come across a case that doesn't work out with `fqtools count` I'll reopen this ticket but for now `count` should do the trick. 👍
